# input = """abcde
# fghij
# klmno
# pqrst
# axcye
# wvxyz
# fguij"""
input = """bazvmqthjtrnlosiecxyghkwud
pazvmqbijirzlosiecxyghkwud
pazvtqbmjtrnlosiecxyghkwzd
pazvmqbfjtrjlosnlcxyghkwud
pazvkqbfjtrtlosiecjyghkwud
paztmqbfjtrnbosiecxyglkwud
pazvmqbfjtunlosievxmghkwud
pazvmqbfjtmngosiecyyghkwud
jazvmqbfjtrnlosiecxygikpud
pazvqqbfctrnlosimcxyghkwud
pazvmqbfjtrnwogiecxyihkwud
pazvmqbfjtrqlojiecxeghkwud
payvmqbfjtrzlosiecxyghkwuk
pkzvmqnfjtrnlosieciyghkwud
pazvmqqfjtrnldsiecxyghkwui
pazvmqbfttrqlosiecxywhkwud
gazvmybfjthnlosiecxyghkwud
pazvmqbfjtrnlasiecxygptwud
pktvmqbfjtrnwosiecxyghkwud
pazvmqwfjtrnlosiecxgghkkud
pazvmzkbjtrnlosiecxyghkwud
pazvmqbfjtrnloslecxyghuwui
pezvmqbfjtrnlesieyxyghkwud
cazvmqbfjrrnlosiecxyghkmud
pazvmqrfjjrnlosiecxyghkwnd
pazvmqbgjtrnlosiecxyphtwud
pazvmqbvmtrnlosiecxyghkpud
pazdmqbfjtrnlosiecxyuhkpud
pazvmqbflnrnloshecxyghkwud
pazvvqbfjprilosiecxyghkwud
pazvwqbfjtrllosiecxyghknud
pazvmqbfjtrnloniecxdghkaud
pazvmqbfjtrnlvsuecxynhkwud
ptzvmqwfjtrnlosieccyghkwud
pkzvmqbjjtrnlosiecryghkwud
pazvmqqfjtrexosiecxyghkwud
pazgmqbfjtrneoyiecxyghkwud
paznmqbfjtrnlosiecxydhkwzd
pazvmqbfjtrnaosiwcxsghkwud
pazomqbfjxrnlosiewxyghkwud
pazsmqbfjprnlosiecxrghkwud
pazvmqbfqtrnoosiecxygmkwud
aazvmqbfjtrnlosiacxyghjwud
pazviqbfjtrnlobiecxygrkwud
qazwmqbfjhrnlosiecxyghkwud
pazvmqbfftrnlosiqcxygfkwud
patvmqbfjtonlosircxyghkwud
pazvmqbfjtrnlomaecxyghkpud
paztmqbfjtrulossecxyghkwud
pazvmqbijtrnlobiecxyghkwkd
pazvsqbfjtrnlospecxyghkqud
pbzmmqbfjtrnlosiecxyghkwhd
pezvkqbfjtenlosiecxyghkwud
razvmqbfjkrnlosiecxeghkwud
pazcmqbfjtrnloriecxyghkgud
pazvmqbfftfnlosiecvyghkwud
pazvmqpujtrnlosiepxyghkwud
patvgqbfjtrnloslecxyghkwud
pazvmqbfltrnlosibcxyghswud
pazvmebfjtrnlosaecxyehkwud
pazdmqbejtrnlosiecxyghrwud
pazvmcbfntrplosiecxyghkwud
pszvmqbfjtrnlosivcfyghkwud
puzvmqbfjtrnloeiecxyxhkwud
pazvmqbfjtrivooiecxyghkwud
pazvyqbfjtrngosiwcxyghkwud
pauvmqbfjtrnlosimexyghkwud
pazvmqbfjtrnwoshecxeghkwud
dazvmqbfjtrnloshecxygxkwud
pazvmqbfjtrtdosiecxyghvwud
pazxmqbfjtrnlosieceyghjwud
pazvmqbfjtrnlosihexjghkwud
pazvmqbfjsrnlosiecxughiwud
phzvcqbfjtrqlosiecxyghkwud
pazvmibfjtrnlosjecxxghkwud
pazvmqbfjtrbeosiecxlghkwud
pazvmqyfjttolosiecxyghkwud
fawvmqbfjtrnlosiecxyghkwhd
pazvmqbfjprnxosiecxyghkbud
macvmqbfjtrnlosiesxyghkwud
pazsmqbfjtrflouiecxyghkwud
pacvmqbfjtrnltsiecxyghcwud
pazvmqbfjtymlosiecxygykwud
pazvmqbfjtrclosiecxygukwmd
pazvmqbfjtrnlobiecxphhkwud
mazvmqbhitrnlosiecxyghkwud
pazvmqdtjtrnlrsiecxyghkwud
pazvmqbfjgrnllsieczyghkwud
pazvmqbfjtrilosiecxxgikwud
pazvmqbjjtrnlosreceyghkwud
paxvmmbfjtrilosiecxyghkwud
pazqmwbfjtrnlowiecxyghkwud
pazvmqbfjfrnqosiecxyghkwui
pazvmqbfjtrrgosiecxyghswud
pazvmqnfjtrnlosiecsyghkwmd
paiemqbmjtrnlosiecxyghkwud
pazvmqbfdtqnlosiecxyjhkwud
pazvmxbfjthndosiecxyghkwud
pqzvmqbfjtrnlosiecxbghkzud
pagrmqbfjtrnlosiecxygskwud
pazamqtfjtrnsosiecxyghkwud
pazvmqbfjtrnldshecxyzhkwud
pazvmnbfjtrllosieclyghkwud
snzvmqbfjnrnlosiecxyghkwud
pazvsqbfjdrnlosiecxyghswud
pazvmqnfjfrnlosiecsyghkwud
pazvmqbfjtrnlosiecxjghowum
pazvmqbfjtjnlosieczygfkwud
pazvmqbsjtrnloziecxyghkeud
pazvxqbgjtrnlooiecxyghkwud
pazvmqbfjtrnlooiecxmyhkwud
pazvmqbyftrnlosgecxyghkwud
pazvmqbfjtrnlosiwcxyqhksud
pazvmqkyjtrnlokiecxyghkwud
pazfmqbfjtrnlosijcxyohkwud
pazvmqbfjtrnlociecxygikcud
fazvmqbfjtrnlosiecxyjhkuud
pazvmqbojtknlohiecxyghkwud
pazvmqbfjtgnlosbecxyghkwux
pazvmqbfjtrnlocieckoghkwud
pazvdqbfjtrlltsiecxyghkwud
pazvmqbfjtsnlfsiecxyglkwud
przvpqbfjtrnyosiecxyghkwud
pazvmbrfjtrnlosiecxmghkwud
dazvmqbfttrnlostecxyghkwud
pazvmqbfttdnlosiecxygwkwud
pazvmqbvitrnlosieexyghkwud
pazvmqbfjhrnlosjecxyvhkwud
pazvmqbfstrnlosiecxyggkwpd
bazvmqbfjtrnlmsiecxyohkwud
patmmqbfjtrnlosizcxyghkwud
pazvmqbfwtrglosieqxyghkwud
pazvmqbfjtrnlosiecxdhhkwmd
pazvmqbfjdrnlosnexxyghkwud
oazrrqbfjtrnlosiecxyghkwud
pazvmqbfjcrnlosiecxygakwjd
pazvmqbfjtrnlosifcxfghkwyd
pazvmnbfjtrnlosiecxyahzwud
pazvmqbfgtrnlojiecxyghkgud
pazvmqbfjtrnlaliecxyghkwuy
pazvmqbfjtrnlfsiecrtghkwud
pazvmqbkjtrnloswecxdghkwud
pazvtqbfjtdnlosiecxyghkwuu
pozvmqbfrtrnlosiesxyghkwud
payvmqbfjornlossecxyghkwud
pazvuqbfjtrnlosiscxyghkpud
pgzcmqbfjtrnlotiecxyghkwud
pazvvqbfjtrnlobieyxyghkwud
pazycqbfjtrnlosiecxyzhkwud
pizvdqbfjtrnlosiecxbghkwud
pazvmqbfjtrnloqiecxmgtkwud
gazvmqbfjtrnlusiecxpghkwud
pazvmqdfjtralosiecxyghkwmd
pazvmqbfjtmnlosiecxywhawud
pazvlqbfjtrnlosqecxyghqwud
pazvmqbfjtrnlhsneixyghkwud
kazvmqbfjtrqlosimcxyghkwud
pazvmwbfjtrclosiecxyghkuud
pazvmqjfjtrnlosieckyghpwud
pezvmqbgjtrnloseecxyghkwud
pazvqqbfjtfnlosvecxyghkwud
oazvmqbfjtunlosiecxyghkwad
pazvmqbfjtrncoswecxyghfwud
pazvyqbfjtrnlosqecxygtkwud
pazvmqbfjtrvlzsiecxygwkwud
pazvmqbfjjrnlosiekxylhkwud
madvmqbfjtrnlosircxyghkwud
pazvmybfjtrnlisiecxyghkwbd
pazvmqbjjixnlosiecxyghkwud
pazvmqefjtrnloqiecxyghhwud
pazveqbfjtrnlosiecgygzkwud
pazvmqbfjtrxlosiecxmgwkwud
uazvmqufjtrnlosiecxyghkwuo
pasymqbfjtrnlosiecxyghowud
pazvmqbfjtlnlpsiecxyghswud
pnzvmqbfjprnloszecxyghkwud
pafjmqcfjtrnlosiecxyghkwud
pazvmqxfbtrnloqiecxyghkwud
pazvmzbfjtrnposiccxyghkwud
pazvmqbfjotulosiecxyghkwud
pazvmqbfotrnlosgecxykhkwud
przvmqbfjtrnlosiecxyqhkwcd
pazvmqbfjtsnlogiecxyyhkwud
pazvmqbfrtrnlzsiecxyghkwug
pazvmqbfjtrnlosiecxzgukwuo
pqzvmqbqjtrnlosdecxyghkwud
pazvmqbfjtqqlosiecxughkwud
pazvmqbfjtrnlosiedhyphkwud
pazsmqbcutrnlosiecxyghkwud
pazvmqbgrtrnlosiecxyghpwud
pazemqbfjtznlosiecxyghkvud
pazvkqbfjtrilosiecxyghkwod
pfzvmqbfjtrnlopiecxygjkwud
pazvmqvfjtreloniecxyghkwud
pazvmqbfjernljsiecxgghkwud
pazvmqikjtrnlosiecxyghqwud
pazvmqbfjtrnpesoecxyghkwud
fazvmqbfjtrnlosihchyghkwud
pazvmqbfjtgnloanecxyghkwud
pazvmqsfjqrnlosiecxychkwud
parvmqbfjtrnlosiecxygfuwud
przvmqbfjtrhlosihcxyghkwud
pazvmqbcjtrnlosimcxgghkwud
pazvmqbfjtrnlosceciyjhkwud
pazvkqbfjtrylosivcxyghkwud
pazvmqbfjtrnlgsieoxyghdwud
pazvmqnfstrnlowiecxyghkwud
pazvmqbfdtrnlosieumyghkwud
pazvmqbfjtrnlosyecxfghkwul
pazvmqbfjtrclosivcxyghkcud
pazjmqbfjtrnlosiecxygokwkd
hazvmqbfjtrflosiecxzghkwud
wazvmqbfjtrnlomiecxyphkwud
yazvmqbfjirnkosiecxyghkwud
pczvmqbfjtrnlohiecxyghkwpd
pazvmqbfotrbeosiecxlghkwud
pazvmqbfjtrplosiecxynhzwud
paxvbqbwjtrnlosiecxyghkwud
pazvmqvfjtrnlosiecbyghqwud
pazjmqbfjtrnlosiecxoghkwed
pazvmqbfjtreljsitcxyghkwud
mazamqbfjtrnlosiecxoghkwud
pazvmqbfjjrnposiscxyghkwud
pbrvmqbfjtrnloliecxyghkwud
pazvmqbfjtrnlosiecxgghkyyd
pmzvmqbfntrnlosiecxyghkwuw
pazvzqbfjtrnlosienxyghzwud
pazvmqifjtvnlosrecxyghkwud
tazvmqbhjtjnlosiecxyghkwud
pazvmqbfjtlnxosiecxyghkwuo
pazvmqbfjennlosiecxyghkwxd
pahvmqbfjhrnlosiecxythkwud
pazvmlkfjtrnlxsiecxyghkwud
pfzvmqbojtrnlosieciyghkwud
pazvbqbfjtrollsiecxyghkwud
eazvmqbfjtrnlosiecayghkoud
pazvmqbfjtjnlvsiecxyghkwsd
pazvoqbojtrnlosiecfyghkwud
pazvmqbfjtuslosiecxyghksud
pazvmqbfjnrnlosiedxyghkwup
pazvmqbjjtrnlosieaxyghdwud
pazccqbfjtrhlosiecxyghkwud
pbzvmqkfjtrnlosievxyghkwud
pazvmqrljtrnlosiscxyghkwud
pazvmqbfjfoqlosiecxyghkwud
pazcmqbfjtrnlosiecxyihkwuf
pszvmqbfjtrnnosiacxyghkwud
aazvmqbfjtrnlosieyxyghkwld
pazvrqbfntrnlosiycxyghkwud
pkzvoqbfjtrnlosiecxyghxwud"""


ids = input.split()
strings_with_less_than_1_char_diff = []
list_index = 0
while list_index < len(ids) - 1:
    each = ids[list_index]
    inner_loop_index = list_index + 1
    while inner_loop_index < len(ids):
        compare = ids[inner_loop_index]
        char_index = 0
        count_diff = 0
        while char_index < len(each):
            if each[char_index] != compare[char_index]:
                count_diff += 1
            char_index = char_index + 1
            if count_diff == 2:
                break
        if count_diff < 2:
            strings_with_less_than_1_char_diff.append((each, compare))
        inner_loop_index = inner_loop_index + 1
    list_index = list_index + 1

print(strings_with_less_than_1_char_diff)
